# Generated by Django 3.2 on 2021-04-07 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='dynamic_images')),
                ('label', models.CharField(choices=[('SE', 'Shoes'), ('ST', 'Shirt'), ('PT', 'Pant')], max_length=2)),
                ('price', models.FloatField()),
                ('brand', models.CharField(choices=[('ZOD', 'Zodiac'), ('PAN', 'Park Avenue'), ('NKE', 'Nike'), ('ADS', 'Adidas'), ('SPR', 'Spykar'), ('GSR', 'Gstar')], max_length=3)),
                ('description', models.TextField()),
                ('remaining_stock', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Product',
                'db_table': 'product',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('created_on', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_code', models.CharField(blank=True, max_length=250, null=True)),
                ('color', models.CharField(choices=[('RD', 'Red'), ('WE', 'White'), ('GY', 'Gray'), ('YW', 'Yellow'), ('BK', 'Black')], max_length=2)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra_Large')], max_length=2)),
                ('gender_category', models.CharField(choices=[('M', 'Mens'), ('F', 'Womens')], max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'verbose_name': 'Skus',
                'verbose_name_plural': 'Sku',
                'db_table': 'sku',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sku')),
            ],
            options={
                'verbose_name': 'Batchs',
                'verbose_name_plural': 'Batch',
                'db_table': 'batch',
            },
        ),
    ]
